version: '2'
services:
  qgisserver:
    image: opengisch/qgis-server:3.30-jammy
    volumes:
      - ./dem.tif:/dem.tif
      - ./data.gpkg:/data.gpkg
      - ./projects/qsa:/io/data
      - ../qsa-plugin:/io/plugins/qsa
      - ./pg_service.conf:/etc/postgresql-common/pg_service.conf
    environment:
      - QGIS_USER=1000
      - QGIS_SERVER_LOG_LEVEL=0
      - QGIS_SERVER_PROJECT_CACHE_STRATEGY=periodic
      - QSA_HOST="qsa"
      - QSA_PORT=9999
  qsa:
    image: pblottiere/qsa
    entrypoint: "qsa"
    build:
      context: ..
      dockerfile: sandbox/Dockerfile
    volumes:
      - ./dem.tif:/dem.tif
      - ./data.gpkg:/data.gpkg
      - ./projects/qsa:/projects
      - ./pg_service.conf:/root/.pg_service.conf
    ports:
      - 5000:5000
    environment:
      - QSA_QGISSERVER_URL=http://qgisserver/ogc/
      - QSA_QGISSERVER_PROJECTS_DIR=/projects
      - QSA_QGISSERVER_PROJECTS_PSQL_SERVICE=qsa
      - QSA_QGISSERVER_MONITORING_PORT=9999
      - QSA_MAPPROXY_PROJECTS_DIR=
  postgres:
    image: postgis/postgis:15-3.4-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=qsa
      - POSTGRES_USER=qsa
      - POSTGRES_DB=qsa
