version: '2'
services:
  qgisserver:
    image: opengisch/qgis-server:3.30-jammy
    volumes:
      - ./projects/qgis:/io/data
      - ../qsa-plugins:/io/plugins/qsa
    environment:
      - QGIS_USER=1000
      - QGIS_SERVER_LOG_LEVEL=0
      - QSA_HOST="qsa"
      - QSA_PORT=9999
  qsa:
    image: pblottiere/qsa
    entrypoint: "qsa"
    build:
      context: ..
      dockerfile: sandbox/Dockerfile
    volumes:
      - ./projects/qgis:/projects
    ports:
      - "5000:5000"
    environment:
      - QSA_QGISSERVER_URL=http://qgisserver
      - QSA_QGISSERVER_PROJECTS=/projects
      - QSA_QGISSERVER_MONITORING_PORT=9999
      - QSA_MAPPROXY_PROJECTS=
